import type { BlockTypeDefinition, BlockType } from '../types';

export const flow: Partial<Record<BlockType, BlockTypeDefinition>> = {
  group: {
    type: 'group',
    label: 'Group',
    icon: 'FolderOpen',
    description: 'Organize test steps into a named group for better reporting',
    color: 'amber',
    canHaveChildren: true,
    defaultProperties: { name: '' },
    fields: [
      { key: 'name', label: 'Group Name', type: 'string', placeholder: 'e.g. User Login Flow', required: true },
    ],
  },
  loop: {
    type: 'loop',
    label: 'Loop',
    icon: 'Repeat',
    description: 'Repeat child steps a specified number of times or while a condition holds',
    color: 'orange',
    canHaveChildren: true,
    defaultProperties: { count: 1, whileCondition: '' },
    fields: [
      { key: 'count', label: 'Iterations', type: 'number', placeholder: 'Number of iterations', defaultValue: 1 },
      { key: 'whileCondition', label: 'While Condition (optional)', type: 'string', placeholder: '__ITER < 10' },
    ],
  },
  condition: {
    type: 'condition',
    label: 'Conditional',
    icon: 'GitBranch',
    description: 'Execute children only if a condition is met',
    color: 'rose',
    canHaveChildren: true,
    defaultProperties: { expression: '', elseEnabled: false, elseBlocks: [] },
    fields: [
      { key: 'expression', label: 'If Expression', type: 'code', placeholder: 'e.g. response.status === 200', required: true },
    ],
  },
  transaction: {
    type: 'transaction',
    label: 'Transaction',
    icon: 'Timer',
    description: 'Measure total duration of child blocks as a single metric',
    color: 'violet',
    canHaveChildren: true,
    defaultProperties: { name: '' },
    fields: [
      { key: 'name', label: 'Transaction Name', type: 'string', placeholder: 'e.g. Checkout Flow', required: true },
    ],
  },
  throughput: {
    type: 'throughput',
    label: 'Throughput',
    icon: 'Percent',
    description: 'Execute children only a percentage of iterations or N times',
    color: 'amber',
    canHaveChildren: true,
    defaultProperties: { mode: 'percent', percent: 50, totalExecutions: 0 },
    fields: [
      { key: 'mode', label: 'Mode', type: 'select', options: [
        { label: 'Percent of iterations', value: 'percent' },
        { label: 'Total executions', value: 'total' },
      ]},
      { key: 'percent', label: 'Percent', type: 'number', placeholder: '50' },
      { key: 'totalExecutions', label: 'Total Executions', type: 'number', placeholder: '10' },
    ],
  },
  interleave: {
    type: 'interleave',
    label: 'Interleave',
    icon: 'ListOrdered',
    description: 'Execute one child at a time, round-robin across iterations',
    color: 'cyan',
    canHaveChildren: true,
    defaultProperties: {},
    fields: [],
  },
  'random-controller': {
    type: 'random-controller',
    label: 'Random',
    icon: 'Shuffle',
    description: 'Execute one random child each iteration',
    color: 'pink',
    canHaveChildren: true,
    defaultProperties: {},
    fields: [],
  },
  'switch': {
    type: 'switch',
    label: 'Switch',
    icon: 'ArrowLeftRight',
    description: 'Execute children based on a selector value (0-based index)',
    color: 'orange',
    canHaveChildren: true,
    defaultProperties: { selector: '' },
    fields: [
      { key: 'selector', label: 'Selector Expression', type: 'code', placeholder: 'e.g. Math.floor(Math.random() * 3) or __ITER % 3', required: true },
    ],
  },
  'for-each': {
    type: 'for-each',
    label: 'For Each',
    icon: 'IterationCw',
    description: 'Iterate over an array, executing children for each item',
    color: 'teal',
    canHaveChildren: true,
    defaultProperties: { array: '', itemVar: 'item', indexVar: 'index' },
    fields: [
      { key: 'array', label: 'Array Expression', type: 'code', placeholder: 'e.g. JSON.parse(res.body).items', required: true },
      { key: 'itemVar', label: 'Item Variable Name', type: 'string', placeholder: 'item' },
      { key: 'indexVar', label: 'Index Variable Name', type: 'string', placeholder: 'index' },
    ],
  },
  'once-only': {
    type: 'once-only',
    label: 'Once Only',
    icon: 'MinusCircle',
    description: 'Execute children only once per VU (set up before iterations)',
    color: 'slate',
    canHaveChildren: true,
    defaultProperties: {},
    fields: [],
  },
  runtime: {
    type: 'runtime',
    label: 'Runtime',
    icon: 'Clock',
    description: 'Execute children for a specified duration (ms)',
    color: 'yellow',
    canHaveChildren: true,
    defaultProperties: { durationMs: 5000 },
    fields: [
      { key: 'durationMs', label: 'Duration (ms)', type: 'number', placeholder: '5000', required: true },
    ],
  },
  'synchronizing-timer': {
    type: 'synchronizing-timer',
    label: 'Sync Timer',
    icon: 'Timer',
    description: 'Block VUs until N are ready (synchronization point)',
    color: 'orange',
    canHaveChildren: true,
    defaultProperties: { vuCount: 5, timeout: '30000' },
    fields: [
      { key: 'vuCount', label: 'VU Count', type: 'number', placeholder: '5', required: true, defaultValue: 5 },
      { key: 'timeout', label: 'Timeout (ms)', type: 'number', placeholder: '30000', defaultValue: 30000 },
    ],
  },
};
