import type { BlockTypeDefinition, BlockType } from '../types';

export const requests: Partial<Record<BlockType, BlockTypeDefinition>> = {
  'http-request': {
    type: 'http-request',
    label: 'HTTP Request',
    icon: 'Globe',
    description: 'Send an HTTP request (GET, POST, PUT, DELETE, PATCH, HEAD, OPTIONS)',
    color: 'blue',
    canHaveChildren: true,
    defaultProperties: { method: 'GET', url: '', headers: [], body: '', params: {} },
    fields: [
      { key: 'method', label: 'Method', type: 'select', required: true, options: [
        { label: 'GET', value: 'GET' }, { label: 'POST', value: 'POST' },
        { label: 'PUT', value: 'PUT' }, { label: 'DELETE', value: 'DELETE' },
        { label: 'PATCH', value: 'PATCH' }, { label: 'HEAD', value: 'HEAD' },
        { label: 'OPTIONS', value: 'OPTIONS' },
      ]},
      { key: 'url', label: 'URL', type: 'string', placeholder: 'https://api.example.com/users', required: true },
      { key: 'headers', label: 'Headers', type: 'headers', placeholder: 'Add header...' },
      { key: 'body', label: 'Body', type: 'code', placeholder: 'Request body (JSON, text, etc.)' },
      { key: 'tag', label: 'Tag', type: 'string', placeholder: 'Optional request tag' },
      { key: 'timeout', label: 'Timeout (ms)', type: 'number', placeholder: '60000' },
    ],
  },
  'http-batch': {
    type: 'http-batch',
    label: 'HTTP Batch',
    icon: 'Layers',
    description: 'Issue multiple HTTP requests in parallel',
    color: 'indigo',
    canHaveChildren: true,
    defaultProperties: {},
    fields: [
      { key: 'tag', label: 'Tag', type: 'string', placeholder: 'Optional batch tag' },
    ],
  },
  'grpc-call': {
    type: 'grpc-call',
    label: 'gRPC Call',
    icon: 'Repeat2',
    description: 'Make a gRPC unary or streaming call',
    color: 'purple',
    canHaveChildren: true,
    defaultProperties: { service: '', method: '', protoFiles: [], body: '', metadata: [] },
    fields: [
      { key: 'service', label: 'Service', type: 'string', placeholder: 'package.ServiceName', required: true },
      { key: 'method', label: 'Method', type: 'string', placeholder: 'MethodName', required: true },
      { key: 'protobuf', label: 'Proto File', type: 'string', placeholder: '/path/to/service.proto' },
      { key: 'body', label: 'Request Body', type: 'json', placeholder: '{"field": "value"}' },
      { key: 'metadata', label: 'Metadata', type: 'headers' },
    ],
  },
  websocket: {
    type: 'websocket',
    label: 'WebSocket',
    icon: 'Radio',
    description: 'Connect and interact via WebSocket — send messages, handle responses, assert on connection status',
    color: 'cyan',
    canHaveChildren: true,
    defaultProperties: { url: '', protocols: '', timeout: '30000', autoReconnect: false, messagesOnOpen: '[]', closeAfterMessages: false, closeAfterCount: 1 },
    fields: [
      { key: 'url', label: 'URL', type: 'string', placeholder: 'wss://ws.example.com', required: true },
      { key: 'protocols', label: 'Protocols', type: 'string', placeholder: 'Optional, comma separated' },
      { key: 'timeout', label: 'Timeout (ms)', type: 'number', placeholder: '30000', defaultValue: 30000 },
      { key: 'messagesOnOpen', label: 'Messages on Open', type: 'json', placeholder: '[{"type":"subscribe","channel":"test"}]' },
      { key: 'closeAfterMessages', label: 'Close after messages', type: 'boolean', defaultValue: false },
      { key: 'closeAfterCount', label: 'Messages before close', type: 'number', placeholder: '1', defaultValue: 1 },
    ],
  },
  'sql-query': {
    type: 'sql-query',
    label: 'SQL Query',
    icon: 'Database',
    description: 'Execute a SQL query against a database (PostgreSQL, MySQL, SQL Server)',
    color: 'emerald',
    canHaveChildren: true,
    defaultProperties: { connectionId: '', query: '', params: '', tag: '' },
    fields: [
      { key: 'connectionId', label: 'DB Connection ID', type: 'string', placeholder: 'UUID from database connections' },
      { key: 'query', label: 'SQL Query', type: 'code', placeholder: 'SELECT * FROM users WHERE id = ?', required: true },
      { key: 'params', label: 'Query Params (JSON)', type: 'json', placeholder: '["value1", 42]' },
      { key: 'tag', label: 'Metric Tag', type: 'string', placeholder: 'Optional tag for custom metrics' },
    ],
  },
  'dummy-sampler': {
    type: 'dummy-sampler',
    label: 'Dummy Sampler',
    icon: 'Beaker',
    description: 'Return a fake response without making a real HTTP request',
    color: 'gray',
    canHaveChildren: false,
    defaultProperties: { statusCode: 200, responseBody: '{"status":"ok"}', responseTime: 0, latency: 0, responseMessage: 'OK', responseHeaders: [] },
    fields: [
      { key: 'statusCode', label: 'Status Code', type: 'number', placeholder: '200', defaultValue: 200 },
      { key: 'responseMessage', label: 'Response Message', type: 'string', placeholder: 'OK', defaultValue: 'OK' },
      { key: 'responseBody', label: 'Response Body', type: 'code', placeholder: '{"status":"ok"}', defaultValue: '{"status":"ok"}' },
      { key: 'responseHeaders', label: 'Response Headers', type: 'headers', placeholder: 'Add response header...' },
      { key: 'latency', label: 'Latency (ms)', type: 'number', placeholder: '0', defaultValue: 0 },
      { key: 'responseTime', label: 'Response Time (ms)', type: 'number', placeholder: '0', defaultValue: 0 },
    ],
  },
  'header-manager': {
    type: 'header-manager',
    label: 'Header Manager',
    icon: 'ListPlus',
    description: 'Set default HTTP headers for all requests in scope',
    color: 'indigo',
    canHaveChildren: false,
    defaultProperties: { headers: [{ key: '', value: '' }] },
    fields: [
      { key: 'headers', label: 'Headers', type: 'headers', placeholder: 'Add default header...' },
    ],
  },
  'cookie-manager': {
    type: 'cookie-manager',
    label: 'Cookie Manager',
    icon: 'CircleDot',
    description: 'Set cookies for a domain before subsequent requests',
    color: 'amber',
    canHaveChildren: false,
    defaultProperties: { domain: '', cookies: [{ key: '', value: '', path: '/' }] },
    fields: [
      { key: 'domain', label: 'Domain URL', type: 'string', placeholder: 'https://example.com', required: true },
      { key: 'cookies', label: 'Cookies', type: 'headers', placeholder: 'Add cookie...' },
    ],
  },
  'cache-manager': {
    type: 'cache-manager',
    label: 'Cache Manager',
    icon: 'Database',
    description: 'Control HTTP caching behavior for subsequent requests',
    color: 'slate',
    canHaveChildren: false,
    defaultProperties: { mode: 'default' },
    fields: [
      { key: 'mode', label: 'Cache Mode', type: 'select', options: [
        { label: 'Default', value: 'default' },
        { label: 'Disabled (no-cache)', value: 'disabled' },
        { label: 'Force Reload', value: 'force-reload' },
      ]},
    ],
  },
  'auth-manager': {
    type: 'auth-manager',
    label: 'Authorization Manager',
    icon: 'KeyRound',
    description: 'Configure authentication for HTTP requests (Basic, Bearer, API Key, OAuth2)',
    color: 'indigo',
    canHaveChildren: false,
    defaultProperties: {
      authType: 'bearer',
      token: '',
      username: '',
      password: '',
      keyName: 'X-API-Key',
      keyValue: '',
      tokenUrl: '',
      clientId: '',
      clientSecret: '',
      scopes: '',
    },
    fields: [
      { key: 'authType', label: 'Auth Type', type: 'select', options: [
        { label: 'Bearer Token', value: 'bearer' },
        { label: 'Basic Auth', value: 'basic' },
        { label: 'API Key', value: 'api-key' },
        { label: 'OAuth2 (Client Credentials)', value: 'oauth2' },
      ]},
      { key: 'token', label: 'Token', type: 'string', placeholder: 'eyJhbGciOiJSUzI1NiIs...', showIf: { key: 'authType', value: 'bearer' } },
      { key: 'username', label: 'Username', type: 'string', placeholder: 'admin', showIf: { key: 'authType', value: 'basic' } },
      { key: 'password', label: 'Password', type: 'string', placeholder: '••••••••', showIf: { key: 'authType', value: 'basic' } },
      { key: 'keyName', label: 'Header Name', type: 'string', placeholder: 'X-API-Key', showIf: { key: 'authType', value: 'api-key' } },
      { key: 'keyValue', label: 'Value', type: 'string', placeholder: 'your-api-key', showIf: { key: 'authType', value: 'api-key' } },
      { key: 'tokenUrl', label: 'Token URL', type: 'string', placeholder: 'https://auth.example.com/oauth/token', showIf: { key: 'authType', value: 'oauth2' } },
      { key: 'clientId', label: 'Client ID', type: 'string', showIf: { key: 'authType', value: 'oauth2' } },
      { key: 'clientSecret', label: 'Client Secret', type: 'string', showIf: { key: 'authType', value: 'oauth2' } },
      { key: 'scopes', label: 'Scopes', type: 'string', placeholder: 'openid profile email', showIf: { key: 'authType', value: 'oauth2' } },
    ],
  },
  'http-defaults': {
    type: 'http-defaults',
    label: 'HTTP Request Defaults',
    icon: 'Settings2',
    description: 'Set common HTTP request settings (base URL, default params, timeout)',
    color: 'blue',
    canHaveChildren: false,
    defaultProperties: { baseUrl: '', defaultTimeout: '', defaultHeaders: [], defaultParams: '' },
    fields: [
      { key: 'baseUrl', label: 'Base URL', type: 'string', placeholder: 'https://api.example.com' },
      { key: 'defaultTimeout', label: 'Default Timeout (ms)', type: 'string', placeholder: '60000' },
      { key: 'defaultHeaders', label: 'Default Headers', type: 'headers', placeholder: 'Add default header...' },
      { key: 'defaultParams', label: 'Default Query Params (JSON)', type: 'code', placeholder: '{"api_version": "v2"}' },
    ],
  },
};
